### ISSUE TITLE
provider-nop

### ISSUE THREAD

**Issue by hasheddan** [crossplane/test#11]
`provider-nop` is a Crossplane provider that does exactly what you tell it to. It can be used for testing functionality in core Crossplane without needing to account for requirements of external APIs. It should support a single managed resource that contains a spec that allows for specifying how and when the status of the resource is changed.

**Comment by negz** [comment]
Cross referencing https://github.com/negz/provider-nop, which I put together a long time ago. It's quite out of date, and doesn't do a lot of what I think we want from the new provider-nop @rahulgrover99 is working on.

**Comment by rahulgrover99** [comment]
@hasheddan I hope we can close this issue now :)  Just for reference, the provider can be found [here.](https://github.com/crossplane-contrib/provider-nop)

**Comment by jbw976** [comment]
That sounds quite reasonable to me @rahulgrover99, thanks for your efforts on provider-nop! :)
